"""Conversation session"""


class ConversationSession:

    def __init__(self):
        """Start a fresh, empty conversation session."""

        self.history = []

    def add_scammer_message(self, message: str):
        """
        Record the latest raw scammer message.

        This is the analyst-pasted payload that arrives on /analyze.
        """

        self.history.append({
            "role": "scammer",
            "message": message
        })

    def add_traceai_reply(self, reply: str):
        """
        Record the persona reply generated by the ConversationAgent.
        """

        self.history.append({
            "role": "traceai",
            "message": reply
        })

    def get_history(self) -> str:
        """
        Serialise the whole dialogue into one readable transcript
        block, e.g.::

            SCAMMER: Dear SBI customer, your card is blocked...
            TRACEAI: Can you tell me how to verify this?

        The transcript is injected into the LLM prompt so the
        persona reply stays consistent with prior turns.
        """

        if not self.history:
            return "No previous conversation."

        history = ""

        for item in self.history:

            history += (
                f"{item['role'].upper()}: "
                f"{item['message']}\n"
            )

        return history

    def clear(self):
        """Reset the session (used on a new investigation)."""

        self.history.clear()
